"""Initial schema

Revision ID: 5fe46cae3ec3
Revises: 
Create Date: 2026-02-02 14:08:13.542043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '5fe46cae3ec3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('buildings',
    sa.Column('building_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('building_id')
    )
    op.create_table('devices',
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('building_id', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    op.create_table('raw_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.String(length=64), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('building_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_raw_events_device_timestamp', 'raw_events', ['device_id', 'timestamp'], unique=False)
    op.create_index('idx_raw_events_received_at', 'raw_events', ['received_at'], unique=False)
    op.create_index(op.f('ix_raw_events_event_id'), 'raw_events', ['event_id'], unique=True)
    op.create_index(op.f('ix_raw_events_id'), 'raw_events', ['id'], unique=False)
    op.create_table('normalized_measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_event_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=100), nullable=False),
    sa.Column('building_id', sa.String(length=100), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metric_type', sa.String(length=50), nullable=False),
    sa.Column('value', sa.Numeric(precision=15, scale=6), nullable=False),
    sa.Column('unit', sa.String(length=20), nullable=False),
    sa.Column('delta_value', sa.Numeric(precision=15, scale=6), nullable=True),
    sa.Column('quality_flags', postgresql.ARRAY(sa.String()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('NOW()'), nullable=False),
    sa.ForeignKeyConstraint(['raw_event_id'], ['raw_events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('device_id', 'metric_type', 'timestamp', name='uq_device_metric_timestamp')
    )
    op.create_index('idx_normalized_building_time', 'normalized_measurements', ['building_id', 'timestamp'], unique=False)
    op.create_index('idx_normalized_device_metric_time', 'normalized_measurements', ['device_id', 'metric_type', 'timestamp'], unique=False)
    op.create_index('idx_normalized_quality_flags', 'normalized_measurements', ['quality_flags'], unique=False, postgresql_using='gin')
    op.create_index(op.f('ix_normalized_measurements_id'), 'normalized_measurements', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_normalized_measurements_id'), table_name='normalized_measurements')
    op.drop_index('idx_normalized_quality_flags', table_name='normalized_measurements', postgresql_using='gin')
    op.drop_index('idx_normalized_device_metric_time', table_name='normalized_measurements')
    op.drop_index('idx_normalized_building_time', table_name='normalized_measurements')
    op.drop_table('normalized_measurements')
    op.drop_index(op.f('ix_raw_events_id'), table_name='raw_events')
    op.drop_index(op.f('ix_raw_events_event_id'), table_name='raw_events')
    op.drop_index('idx_raw_events_received_at', table_name='raw_events')
    op.drop_index('idx_raw_events_device_timestamp', table_name='raw_events')
    op.drop_table('raw_events')
    op.drop_table('devices')
    op.drop_table('buildings')
    # ### end Alembic commands ###
